# Generated by Django 3.0.7 on 2020-08-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_basegossipquestionmodel_image_url'),
    ]

    operations = [

    ]
