# Generated by Django 3.0.7 on 2020-07-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_basevotesmodel'),
        ('question', '0002_auto_20200719_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVote',
            fields=[
                ('basevotesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.BaseVotesModel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='question.Question')),
            ],
            bases=('utils.basevotesmodel', models.Model),
        ),
        migrations.CreateModel(
            name='QuestionCommentVote',
            fields=[
                ('basevotesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.BaseVotesModel')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='question.QuestionComment')),
            ],
            bases=('utils.basevotesmodel', models.Model),
        ),
    ]
