version: "3.7"

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  api:
    build: ./app
    command: "daphne gossips_book.asgi:application -b 0.0.0.0 -p 8000"
    volumes:
      - static_volume:/home/app/api/staticfiles
      - media_volume:/home/app/api/mediafiles
    expose:
      - 8000
    depends_on:
      - db
      - redis-server
    env_file:
      - ./.env.prod

    tty: true
    stdin_open: true
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/app/api/staticfiles
      - media_volume:/home/app/api/mediafiles
    ports:
      - "80:80"
    depends_on:
      - api
  redis-server:
    image: "redis:latest"

volumes:
  static_volume:
  media_volume:
  postgres_data:
