version: "3.3"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn gossips_book.routing:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
    links:
      - redis:redis
    environment:
      - REDIS_HOST=redis
      - DJANGO_SETTINGS_MODULE=gossips_book.settings
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
  redis:
    image: redis:latest
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
      - redis.conf:/usr/local/etc/redis.conf
volumes:
  postgres_data:
  static_volume:
  redis-data:
  redis.conf:
