version: "3.3"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gossips_book
      - POSTGRES_PASSWORD=gossips_book
      - POSTGRES_DB=gossips_book_dev

volumes:
  postgres_data:
