version: "3.3"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    links:
      - redis:redis
    stdin_open: true
    tty: true
    environment:
      - REDIS_HOST=redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gossips_book
      - POSTGRES_PASSWORD=gossips_book
      - POSTGRES_DB=gossips_book_dev
  redis:
    image: redis:latest
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
      - redis.conf:/usr/local/etc/redis.conf

volumes:
  postgres_data:
  redis-data:
  redis.conf:
