version: "3.7"

services:
  wsgi_api:
    build: ./app
    command: sh -c "gunicorn gossips_book.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/api/staticfiles
      - media_volume:/home/app/api/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    stdin_open: true
    tty: true
  asgi_api:
    build: ./app
    command: daphne gossips_book.asgi:application -b 0.0.0.0 -p 5000
    expose:
      - 5000
    depends_on:
      - db
      - wsgi_api
      - redis-server
    env_file:
      - ./.env.prod
    stdin_open: true
    tty: true
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=gossip_book
      - POSTGRES_DB=gossip_book
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/app/api/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - asgi_api
      - wsgi_api
  redis-server:
    image: "redis:latest"

volumes:
  static_volume:
  media_volume:
