# Pull official base image
FROM python:3.8.5-alpine
# set work directory

WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install psycopg2 dependencies
RUN apk add --update --no-cache postgresql-client jpeg-dev
RUN apk update \
    && apk add gcc python3-dev musl-dev jpeg-dev postgresql-client
RUN apk add --no-cache libressl-dev libffi-dev gcc libc-dev linux-headers postgresql-dev musl-dev zlib zlib-dev

# Install dependencies
# RUN pip install --upgrade  pip
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy project
COPY . .
