# Generated by Django 3.0.7 on 2020-07-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
