# Generated by Django 3.0.7 on 2020-07-17 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20200717_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocation',
            old_name='city',
            new_name='user_city',
        ),
        migrations.RenameField(
            model_name='userlocation',
            old_name='country',
            new_name='user_country',
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to=settings.AUTH_USER_MODEL),
        ),
    ]
