# Generated by Django 3.0.7 on 2020-07-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20200717_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='user_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
