# Generated by Django 3.0.7 on 2020-07-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20200717_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='user_city',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='user_country',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
