# Generated by Django 3.0.7 on 2020-07-20 15:18

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('user_profile', '0015_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_topics',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
