# Generated by Django 3.0.7 on 2020-07-24 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_basevotesmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gossips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GossipComment',
            fields=[
                ('basecomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.BaseComment')),
            ],
            bases=('utils.basecomment', models.Model),
        ),
        migrations.AddField(
            model_name='gossip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gossips', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GossipVote',
            fields=[
                ('basevotesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.BaseVotesModel')),
                ('gossip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='gossips.Gossip')),
            ],
            bases=('utils.basevotesmodel', models.Model),
        ),
        migrations.CreateModel(
            name='GossipCommentVote',
            fields=[
                ('basevotesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.BaseVotesModel')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='gossips.GossipComment')),
            ],
            bases=('utils.basevotesmodel', models.Model),
        ),
        migrations.AddField(
            model_name='gossipcomment',
            name='gossip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gossips.Gossip'),
        ),
        migrations.AddField(
            model_name='gossipcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gossip', to=settings.AUTH_USER_MODEL),
        ),
    ]
