# Generated by Django 3.0.7 on 2020-07-19 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0002_auto_20200719_0906'),
        ('gossips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GossipComment',
            fields=[
                ('basecomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.BaseComment')),
                ('gossip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gossips', to='gossips.Gossip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gossip', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('utils.basecomment', models.Model),
        ),
    ]
