# Generated by Django 3.0.7 on 2020-08-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gossips', '0002_auto_20200724_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='gossip',
            name='gossip_type',
            field=models.CharField(choices=[('GOSSIP', 'Gossip'), ('CHEATER', 'Cheater')], default='GOSSIP', max_length=50),
        ),
    ]
