# Generated by Django 3.0.7 on 2020-07-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gossips', '0002_gossipcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gossipcomment',
            name='gossip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gossips.Gossip'),
        ),
    ]
