# Generated by Django 3.0.7 on 2020-07-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_basevotesmodel'),
        ('gossips', '0003_auto_20200719_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='GossipVote',
            fields=[
                ('basevotesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.BaseVotesModel')),
                ('gossip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='gossips.Gossip')),
            ],
            bases=('utils.basevotesmodel', models.Model),
        ),
        migrations.CreateModel(
            name='GossipCommentVote',
            fields=[
                ('basevotesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.BaseVotesModel')),
                ('gossip_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='gossips.GossipComment')),
            ],
            bases=('utils.basevotesmodel', models.Model),
        ),
    ]
