# Generated by Django 3.0.7 on 2020-07-20 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gossips', '0004_gossipcommentvote_gossipvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='gossip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gossips', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
