# Generated by Django 3.0.7 on 2020-07-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gossips', '0005_gossip_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gossipcommentvote',
            old_name='gossip_comment',
            new_name='comment',
        ),
    ]
